worker_processes 1;

events {}

http {
    include     mime.types;

    access_log  logs/access.log;
    error_log   logs/error.log debug;

    server {
        listen       8080;

        location / {
            root   E:\Documents\code\focalpoint\public;
            index  present.html;
            try_files $uri $uri/ =404;
        }

        location = / {
            allow 127.0.0.1;
            deny all;
            root   E:\Documents\code\focalpoint\public;
            index  present.html;
            try_files $uri $uri/ =404;
        }

        location = /view {
            alias   E:\Documents\code\focalpoint\public\view.html;
            add_header Content-Type text/html;
        }

        location = /present.html {
            allow 127.0.0.1;
            deny all;
            root E:\Documents\code\focalpoint\public;
        }

        location /config {
            proxy_pass http://127.0.0.1:5000;
        }

        location /token {
            proxy_pass http://127.0.0.1:5000;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /participants {
            proxy_pass http://127.0.0.1:5000;
        }

        location /logs {
            proxy_pass http://127.0.0.1:5000;
        }
    }
}
