worker_processes 1;

events {}

http {
    include       mime.types;

    access_log  logs/access.log;
    error_log   logs/error.log debug;

    server {
        listen       8080;

        location / {
            root   E:\Documents\code\focalpoint\public;
            index  present.html;
            try_files $uri $uri/ =404;
        }
        
        location = /view {
            alias   E:\Documents\code\focalpoint\public\view.html;
            add_header Content-Type text/html;
        }

        location /token {
            proxy_pass http://127.0.0.1:5000;
        }

        location /rtc {
            proxy_pass http://127.0.0.1:7880;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}
